import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Clock, Radio, Zap, Loader2, ArrowRight } from 'lucide-react';

interface DailyMissionCardProps {
  onClick: () => void;
  isLoading: boolean;
}

export const DailyMissionCard: React.FC<DailyMissionCardProps> = ({ onClick, isLoading }) => {
  const [timeLeft, setTimeLeft] = useState('');

  // Countdown Timer Logic
  useEffect(() => {
    const calculateTimeLeft = () => {
      const now = new Date();
      const tomorrow = new Date(now);
      tomorrow.setDate(tomorrow.getDate() + 1);
      tomorrow.setHours(0, 0, 0, 0);
      
      const diff = tomorrow.getTime() - now.getTime();
      
      const hours = Math.floor((diff / (1000 * 60 * 60)) % 24);
      const minutes = Math.floor((diff / 1000 / 60) % 60);
      
      return `${hours}h ${minutes}m`;
    };

    setTimeLeft(calculateTimeLeft());
    const timer = setInterval(() => setTimeLeft(calculateTimeLeft()), 60000);
    return () => clearInterval(timer);
  }, []);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ scale: 1.02 }}
      onClick={onClick}
      className="relative w-full h-48 md:h-56 rounded-3xl cursor-pointer group overflow-hidden mb-8"
    >
      {/* 1. Golden/Holographic Border Effect */}
      <div className="absolute inset-0 p-[2px] rounded-3xl bg-gradient-to-r from-yellow-400 via-orange-300 to-yellow-500 animate-gradient-xy">
        <div className="absolute inset-0 bg-white/10 blur-md animate-pulse" />
      </div>

      {/* 2. Inner Content Container */}
      <div className="relative h-full w-full bg-slate-900 rounded-[22px] overflow-hidden">
        
        {/* Background Image */}
        <div className="absolute inset-0">
          <img 
            src="https://images.unsplash.com/photo-1495020689067-958852a7765e?q=80&w=2000&auto=format&fit=crop" 
            alt="Breaking News" 
            className="w-full h-full object-cover opacity-60 group-hover:scale-105 transition-transform duration-700"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black via-black/60 to-transparent" />
        </div>

        {/* Content Layer */}
        <div className="absolute inset-0 p-6 md:p-8 flex flex-col justify-between">
            
            {/* Header: Live Badge & Countdown */}
            <div className="flex justify-between items-start">
                <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-red-500/20 border border-red-500/50 backdrop-blur-md">
                    <span className="relative flex h-2 w-2">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-2 w-2 bg-red-500"></span>
                    </span>
                    <span className="text-xs font-bold text-red-200 uppercase tracking-widest">LIVE TREND</span>
                </div>

                <div className="flex items-center gap-2 text-yellow-400 font-mono text-sm font-bold bg-black/40 px-3 py-1 rounded-lg border border-yellow-400/30">
                    <Clock className="w-4 h-4" />
                    <span>Expires in: {timeLeft}</span>
                </div>
            </div>

            {/* Title & Call to Action */}
            <div className="max-w-xl">
                <h3 className="text-3xl md:text-4xl font-display font-bold text-transparent bg-clip-text bg-gradient-to-r from-white via-yellow-100 to-yellow-200 mb-2 drop-shadow-sm">
                    Daily Drop: Global Trends
                </h3>
                <p className="text-slate-300 mb-4 line-clamp-1">
                    Generated by AI • Based on real-time headlines • Advanced Vocabulary
                </p>

                {isLoading ? (
                    <div className="flex items-center gap-2 text-yellow-400 font-bold animate-pulse">
                        <Loader2 className="w-5 h-5 animate-spin" />
                        <span>Connecting to News Feed...</span>
                    </div>
                ) : (
                    <div className="flex items-center gap-2 text-white font-bold group-hover:translate-x-2 transition-transform">
                        <span>Start Daily Mission</span>
                        <ArrowRight className="w-5 h-5 text-yellow-400" />
                    </div>
                )}
            </div>
        </div>
      </div>
    </motion.div>
  );
};